### ISSUE TITLE
fix dashboard issues

### ISSUE THREAD

**Issue by juba0x00** [Hack-Maze/front-end#38]
# TODO
@mahmoud-abo-al-ela 

- [x]  footer should be place as the current challenges width
![image](https://github.com/Hack-Maze/front-end/assets/71707534/c42499a3-4d6e-4ef3-a3d7-8035f3c59e04)
![image](https://github.com/Hack-Maze/front-end/assets/71707534/2e8cd3d7-3008-4209-9aa5-c1b073f892fa)

- [x] account should be the profile image as a circle  not as a word
![image](https://github.com/Hack-Maze/front-end/assets/71707534/8846d6b3-630c-4da9-9754-55ce02ee58cc)
- [x] broken questions chart 

![Image](https://github.com/Hack-Maze/front-end/assets/73611543/a4f153e7-8ee0-4b0f-ba3e-751c39226c57)

- [x] 404 page -> `return to home page` button should redirect to `/dashboard` not `/`

- [x] 404 page -> center the page content 

- [x] move scroll bar to the right 
![Image](https://github.com/Hack-Maze/front-end/assets/73611543/75e65d21-6c9d-4c34-9768-2ae88a457bcd)

@mahmoud-abo-al-ela 

# Done
- [x] fix statistics lines
    - [x] remove the horizontal black line
    - [x] vertical lines should not be under the zero level

![Image](https://github.com/Hack-Maze/front-end/assets/73611543/3f021e06-108c-4b05-a783-e6b398023aa2)

- [x] rounded corners
- [x] increase room card padding 
- [x] remove the hide/show button
![Image](https://github.com/Hack-Maze/front-end/assets/73611543/a960276f-7184-4cc0-80c1-acbfe980024f)
- [x] background image
- [x] cards borders should be red 

- [x] "remove friend" button should be highlighted when hovered over
- [x] this line should be should be a little gray not white decrease the intensity 
![image](https://github.com/Hack-Maze/front-end/assets/71707534/265c146f-6f0c-46b3-b083-f1c2616a0432)

**Comment by Mostafa-ewida** [comment]
- [ ] "remove friend" button should be highlighted when hovered over
![image](https://github.com/Hack-Maze/front-end/assets/71707534/c42499a3-4d6e-4ef3-a3d7-8035f3c59e04)

- [ ]  footer should be place as the current challenges width
 ![image](https://github.com/Hack-Maze/front-end/assets/71707534/2e8cd3d7-3008-4209-9aa5-c1b073f892fa)
![image](https://github.com/Hack-Maze/front-end/assets/71707534/2e8cd3d7-3008-4209-9aa5-c1b073f892fa)

- [ ] account should be the profile image as a circle  not as a word
![image](https://github.com/Hack-Maze/front-end/assets/71707534/8846d6b3-630c-4da9-9754-55ce02ee58cc)

- [ ] this line should be should be a little gray not white decrease the intensity 
![image](https://github.com/Hack-Maze/front-end/assets/71707534/265c146f-6f0c-46b3-b083-f1c2616a0432)

@mahmoud-abo-al-ela
